[env:esp32-2432s028r]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
upload_speed = 115200
build_src_filter = +<*> -<sim_main.cpp>
lib_deps =
  lovyan03/LovyanGFX@^1.1.16
  lvgl/lvgl@^8.3.0
  h2zero/NimBLE-Arduino@^1.4.0

build_flags =
  -D CORE_DEBUG_LEVEL=3
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_CONF_PATH=lightning_lv_conf.h
  -Iinclude
extra_scripts = pre:tools/gen_fw_version.py

[env:obd-sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<sim_main.cpp> +<obd/elm.cpp> +<obd/elm.h>
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.0
  lovyan03/LovyanGFX@^1.1.16

[env:native]
platform = native
test_framework = unity
build_src_filter = -<*>
build_flags =
  -I src
  -I test/fakes
